/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.mps_cli.gradle.plugin

class ConeOfInfluenceComputerTest_02 extends TestBase {

    def "cone of influence computer test"() {
        given:
        settingsFile << ""
        buildFile << '''

plugins {
    id('com.mbeddr.mps_cli')
}

buildModuleDependencies {
   sourcesDir = ['../../../../../../../../../mps_test_projects/mps_cli_lanuse_file_per_root']      
}

computeConeOfInfluence {
   referenceBranchName = "origin/testing/do_not_delete/cone_of_influence_test_02" 
   gitRepoRootLocation = '../../../../../../../../../'
}

task printConeOfInfluence {
    dependsOn computeConeOfInfluence
    doLast {
        def affectedSolutions = computeConeOfInfluence.affectedSolutions
        println "all affected solutions: ${affectedSolutions.collect { it.name }.sort()}"
    }
}
'''

        when:
        runTask("printConeOfInfluence")

        then:
        result.output.contains "Solutions [mps.cli.lanuse.library_top2.msd] do not exist on current branch. The cone of influence is the entire set of solutions."
        result.output.contains "all affected solutions: [mps.cli.lanuse.library_second, mps.cli.lanuse.library_top]"
    }
}
