/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.mps_cli.gradle.plugin

class ConeOfInfluenceComputerTest_01 extends TestBase {

    def buildFileText(String coneOfInfluenceSpec) {
        """
            plugins {
                id('com.mbeddr.mps_cli')
            }
            
            buildModuleDependencies {
               sourcesDir = ['../../../../../../../../../mps_test_projects/mps_cli_lanuse_file_per_root']      
            }
            
            computeConeOfInfluence {
               $coneOfInfluenceSpec 
               gitRepoRootLocation = '../../../../../../../../../'
            }
            
            task printConeOfInfluence {
                dependsOn computeConeOfInfluence
                doLast {
                    def affectedSolutions = computeConeOfInfluence.affectedSolutions
                    println "all affected solutions: \${affectedSolutions.collect { it.name }.sort()}"
                }
            }
        """
    }

    def expectedOutput() {
        "all affected solutions: [mps.cli.lanuse.library_second, mps.cli.lanuse.library_top]"
    }

    def "cone of influence computer test from git diff"() {
        given:
        settingsFile << ""
        buildFile << buildFileText(
                "referenceBranchName = 'origin/testing/do_not_delete/cone_of_influence_test_01'")

        when:
        runTask("printConeOfInfluence")

        then:
        result.output.contains expectedOutput()
    }

    def "cone of influence computer test from file list"() {
        given:
        settingsFile << ""
        buildFile << buildFileText(
                "modifiedFiles = ['mps_test_projects/mps_cli_lanuse_file_per_root/solutions/mps.cli.lanuse.library_top/models/mps.cli.lanuse.library_top.authors_top/_010_classical_authors.mpsr']")

        when:
        runTask("printConeOfInfluence")

        then:
        result.output.contains expectedOutput()
    }
}
