/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.mps_cli.gradle.plugin

class ModelBuildingTest extends TestBase {

    def "solutions build test"() {
        given:
        settingsFile << ""
        buildFile << "$buildPreamble" + '''

task printSolutionsInfo {
    dependsOn buildModel
    doLast {
        def repo = buildModel.repository
        def models = repo.allModels()
        println "all models: ${models.collect { it.name }}"
        
        def allNodes = repo.allNodes()
        println "concepts: ${allNodes.collect { it.concept }}"
        
        def authors = repo.nodesOfConcept("mps.cli.landefs.people.structure.Person")
        println "all authors: ${authors.collect { it.name }}"
    }
}

'''

        when:
        runTask("printSolutionsInfo")

        then:
        result.output.contains("mps_test_projects\\mps_cli_lanuse")

        // check that we have models
        result.output.contains "mps.cli.lanuse.library_top.library_top"
        result.output.contains "mps.cli.lanuse.library_top.authors_top"
        result.output.contains "mps.cli.lanuse.library_second.library_top"

        // check nodes by name
        result.output.contains "Mark Twain"
    }
}
