/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.mps_cli.gradle.plugin

import spock.lang.Specification
import spock.lang.TempDir
import org.gradle.testkit.runner.GradleRunner

/**
 * A simple functional test for the 'org.mps_cli.gradle.plugin.greeting' plugin.
 */
class MpsCliGradlePluginPluginFunctionalTest extends Specification {
    @TempDir
    private File projectDir

    private getBuildFile() {
        new File(projectDir, "build.gradle")
    }

    private getSettingsFile() {
        new File(projectDir, "settings.gradle")
    }

    def "can run task"() {
        given:
        settingsFile << ""
        buildFile << """
plugins {
    id('org.mps_cli.gradle.plugin.greeting')
}

buildModel {
   sourcesDir = '..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\..\\\\mps_test_projects\\\\mps_cli_lanuse'
}
"""

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("buildModel")
        runner.withProjectDir(projectDir)
        def result = runner.build()
        print(result.output)

        then:
        result.output.contains("mps_test_projects\\mps_cli_lanuse")
        result.output.contains("number of solutions: 2")
    }
}
