/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.mps_cli.gradle.plugin

class PluginSmokeTest extends TestBase {

    def "'buildModel' task starts"() {
        given:
        settingsFile << ""
        buildFile << """$buildPreamble"""

        when:
        runTask("buildModel")

        then:
        result.output.contains("mps_test_projects" + File.separator + "mps_cli_lanuse")
        result.output.contains("number of solutions: 2")
    }
}
