/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.mps_cli.gradle.plugin

class PrintLanguageInfoTest extends TestBase {

    def "test languages information saving"() {
        given:
        settingsFile << ""
        buildFile << """ 
plugins {
    id('org.mps_cli.gradle.plugin')
}

buildModel {
   sourcesDir = ['../../../../../../../../../mps_test_projects/mps_cli_lanuse_file_per_root']   
}

printLanguageInfo {
   destinationDir = './../../../../../../' 
}"""

        when:
        runTask("printLanguageInfo")

        then:
        // check that we saved the language info
        result.output.contains "language info saved to"
    }
}
