name: MPS-CLI-PY_CI

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.MPSCLI_GITHUB_PKG_REGISTRY }}

jobs:
  build_mps_cli_py:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install parameterized
      # pip install -r requirements.txt
    - name: Test with unittest
      run: |
        cd mps-cli-py
        python -m unittest discover